apiVersion: v1
kind: Pod
metadata:
  name: maja-pod-billy 
spec:
  containers:
  - name: mypod
    image: gitlab-registry.nrp-nautilus.io/jmduarte/hhh:latest 
    command: ["/bin/bash", "-c", "sleep infinity"]
    resources:
      limits:
        cpu: "4"
        memory: 30Gi
        nvidia.com/gpu: 1
      requests:
        memory: 30Gi
        cpu: "4"
        nvidia.com/gpu: 1
    volumeMounts:
    - mountPath: /maad-vol
      name: maad-vol
  restartPolicy: Never
  volumes:
    - name: maad-vol
      persistentVolumeClaim:
        claimName: maad-vol
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: NotIn
            values:
              - gpn-fiona-mizzou-2.rnet.missouri.edu
              - gpengine-uams.areon.net
              - rci-nrp-gpu-05.sdsu.edu
              - node-2-2.sdsc.optiputer.net
              - hcc-gpengine-shor-c5303.unl.edu
              - node-1-3.sdsc.optiputer.net
              - k8s-a100-01.suncorridor.org
              - k8s-haosu-23.sdsc.optiputer.net
