apiVersion: v1
kind: Pod
metadata:
  name: maja-pod-billy-2gpu
spec:
  securityContext:
    fsGroup: 100
  containers:
  - name: mypod
    image: gitlab-registry.nrp-nautilus.io/jmduarte/hhh:latest
    command: ["/bin/bash", "-c", "sleep infinity"]
    resources:
      limits:
        cpu: "8"
        memory: 16Gi
        nvidia.com/gpu: 2
      requests:
        memory: 16Gi
        cpu: "8"
        nvidia.com/gpu: 2
    volumeMounts:
    - mountPath: /maad-vol
      name: maad-vol
    - mountPath: /home/jovyan/.ssh
      name: git-ssh
      readOnly: true
  restartPolicy: Never
  volumes:
  - name: maad-vol
    persistentVolumeClaim:
      claimName: maad-vol
  - name: git-ssh
    secret:
      secretName: git-ssh
      defaultMode: 0440
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: NotIn
            values:
              - none
