apiVersion: batch/v1
kind: Job
metadata:
  labels:
    jobgroup: hhh-job-train
  name: hhh-job-train-mass-sm-pairwise-validate-on-elias-data
spec:
  backoffLimit: 0
  parallelism: 1
  template:
    spec:
      initContainers:
      - name: init-clone-repo
        image: alpine/git
        command:
        - "/bin/sh"
        - "-c"
        - >
          git clone --single-branch --branch master --recurse-submodules https://github.com/Alexanders101/SPANet /opt/repo/hhh &&
          chown -R 1000:1000 /opt/repo/hhh
        volumeMounts:
        - name: git-repo
          mountPath: /opt/repo
        resources:
          limits:
            cpu: '1'
            memory: 1Gi
          requests:
            cpu: '1'
            memory: 1Gi
      containers:
      - name: training
        image: gitlab-registry.nrp-nautilus.io/jmduarte/hhh:latest 
        command:
        - "/bin/bash"
        - "-c"
        - >
          cd /maad-vol/SPANet &&
          pip install -e . &&
          python -m spanet.train -of /maad-vol/option_files/sm/pairwise_elias.json -l /maad-vol/logs -n sm_pairwise_elias --epochs 500 --gpus 1 --batch_size 4096
        resources:
          limits:
            memory: 8Gi
            cpu: "4"
            nvidia.com/gpu: "1"
          requests:
            memory: 8Gi
            cpu: "4"
            nvidia.com/gpu: "1"
        volumeMounts:
        - name: dshm
          mountPath: /dev/shm
        - mountPath: /maad-vol
          name: maad-vol
        - name: git-repo
          mountPath: /opt/repo
      volumes:
      - name: dshm
        emptyDir:
          medium: Memory
          sizeLimit: 2Gi
      - name: maad-vol
        persistentVolumeClaim:
          claimName: maad-vol
      - name: git-repo
        emptyDir: {}
      restartPolicy: Never
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: NotIn
                values:
                  - none
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: nvidia.com/gpu.product
                operator: In
                values:
                # - NVIDIA-GeForce-GTX-1080
                # - NVIDIA-GeForce-GTX-1080-Ti
                # - NVIDIA-GeForce-GTX-2080-Ti
                - NVIDIA-GeForce-RTX-3090
                - NVIDIA-GeForce-RTX-4090
